# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(416, 300)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 20, 274, 190))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.product = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.product.setObjectName("product")
        self.horizontalLayout.addWidget(self.product)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.count = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.count.setObjectName("count")
        self.horizontalLayout.addWidget(self.count)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.addbutton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.addbutton.setFont(font)
        self.addbutton.setObjectName("addbutton")
        self.verticalLayout_2.addWidget(self.addbutton)
        self.deletebutton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.deletebutton.setFont(font)
        self.deletebutton.setObjectName("deletebutton")
        self.verticalLayout_2.addWidget(self.deletebutton)
        self.save = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.save.setObjectName("save")
        self.verticalLayout_2.addWidget(self.save)
        self.listofproducts = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.listofproducts.setObjectName("listofproducts")
        self.verticalLayout_2.addWidget(self.listofproducts)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Wprowadź produkt"))
        self.label_2.setText(_translate("Dialog", "Wprowadź ilość"))
        self.addbutton.setText(_translate("Dialog", "Dodaj"))
        self.deletebutton.setText(_translate("Dialog", "Usun"))
        self.save.setText(_translate("Dialog", "Zapisz "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
